"""initial ingest_jobs and job_transitions tables

Revision ID: 547e0a5cc6b6
Revises:
Create Date: 2026-04-18 14:49:51.308361+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "547e0a5cc6b6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingest_jobs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("source_url", sa.String(length=2000), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "PENDING",
                "FETCHING",
                "PARSING",
                "CHUNKING",
                "EMBEDDING",
                "INDEXING",
                "COMPLETED",
                "FAILED",
                name="job_state",
                native_enum=False,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("error", sa.String(length=2000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ingest_jobs_source_url"), "ingest_jobs", ["source_url"], unique=False)
    op.create_table(
        "job_transitions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column(
            "from_state",
            sa.Enum(
                "PENDING",
                "FETCHING",
                "PARSING",
                "CHUNKING",
                "EMBEDDING",
                "INDEXING",
                "COMPLETED",
                "FAILED",
                name="job_state",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_state",
            sa.Enum(
                "PENDING",
                "FETCHING",
                "PARSING",
                "CHUNKING",
                "EMBEDDING",
                "INDEXING",
                "COMPLETED",
                "FAILED",
                name="job_state",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("error", sa.String(length=2000), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["ingest_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_transitions_job_id"), "job_transitions", ["job_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_transitions_job_id"), table_name="job_transitions")
    op.drop_table("job_transitions")
    op.drop_index(op.f("ix_ingest_jobs_source_url"), table_name="ingest_jobs")
    op.drop_table("ingest_jobs")
    # ### end Alembic commands ###
